// scripts/generate-avatar-index.mjs
// run: node ./scripts/generate-avatar-index.mjs
import fs from "fs";
import path from "path";

const AVATARS_DIR = path.join(process.cwd(), "src", "avatars");
const OUT_FILE = path.join(process.cwd(), "src", "accAvatars", "index.js");

function slugify(name) {
  return name.replace(/\.[^/.]+$/, "").replace(/[^a-zA-Z0-9_]/g, "_");
}

if (!fs.existsSync(AVATARS_DIR)) {
  console.error("avatars directory not found at", AVATARS_DIR);
  process.exit(1);
}

const files = fs.readdirSync(AVATARS_DIR).filter((f) => f.toLowerCase().endsWith(".svg"));
if (files.length === 0) {
  console.warn("No svg files found in", AVATARS_DIR);
  fs.writeFileSync(OUT_FILE, "export default [];\n");
  process.exit(0);
}

let imports = [];
let entries = [];

files.forEach((file, i) => {
  const varName = `Av_${slugify(file)}`;
  const relPath = `../avatars/${file}`;
  imports.push(`import ${varName} from "${relPath}";`);
  entries.push(`  { id: "${slugify(file)}", Component: ${varName} }`);
});

const content = `// This file is auto-generated by scripts/generate-avatar-index.mjs
// Run the script to refresh when you add/remove SVGs.
${imports.join("\n")}

const avatars = [
${entries.join(",\n")}
];

export default avatars;
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, content, "utf8");
console.log("Generated", OUT_FILE, "with", files.length, "avatars.");
